# WINDOW SETTINGS
WINDOW_SIZE = (1280, 720)
WINDOW_TITLE = "Galactica"
WINDOW_ICON_PATH = None
WINDOW_DEBUG = True

# CAMERA SETTINGS
CAMERA_BACKGROUND_TILE_PATH = None
CAMERA_BACKGROUND_COLOR = (255, 0, 0)
CAMERA_DEBUG = True