# WINDOW SETTINGS
WINDOW_SIZE = (1280, 720)
WINDOW_TITLE = "Galactica"
WINDOW_ICON_PATH = None
WINDOW_DEBUG = True

# CAMERA SETTINGS
CAMERA_BACKGROUND_TILE_PATH = None
CAMERA_BACKGROUND_COLOR = (0, 0, 0)
CAMERA_DEBUG = True

# EVENTS SETTINGS
EVENTS_MAPPING = {
    'WINDOW': [
        'QUIT'
    ],
    'INPUT': [
        'KEYDOWN',
        'KEYUP'
    ]
}
EVENTS_DEBUG = True

# INPUT SETTINGS:
INPUT_DEBUG = True

# LOOP SETTINGS
LOOP_FPS = 60.0
LOOP_DEBUG = True
